// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: BlogService.proto

package GrpcBlogService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogServiceClient interface {
	CreatedBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	MultiGetBlogs(ctx context.Context, in *MultiGetBlogsRequest, opts ...grpc.CallOption) (*MultiGetBlogsResponse, error)
	GetBlogsOfUser(ctx context.Context, in *GetBlogsOfUserRequest, opts ...grpc.CallOption) (*GetBlogsOfUserResponse, error)
}

type blogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogServiceClient(cc grpc.ClientConnInterface) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreatedBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	err := c.cc.Invoke(ctx, "/BlogService/CreatedBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) MultiGetBlogs(ctx context.Context, in *MultiGetBlogsRequest, opts ...grpc.CallOption) (*MultiGetBlogsResponse, error) {
	out := new(MultiGetBlogsResponse)
	err := c.cc.Invoke(ctx, "/BlogService/MultiGetBlogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) GetBlogsOfUser(ctx context.Context, in *GetBlogsOfUserRequest, opts ...grpc.CallOption) (*GetBlogsOfUserResponse, error) {
	out := new(GetBlogsOfUserResponse)
	err := c.cc.Invoke(ctx, "/BlogService/GetBlogsOfUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServiceServer is the server API for BlogService service.
// All implementations must embed UnimplementedBlogServiceServer
// for forward compatibility
type BlogServiceServer interface {
	CreatedBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error)
	MultiGetBlogs(context.Context, *MultiGetBlogsRequest) (*MultiGetBlogsResponse, error)
	GetBlogsOfUser(context.Context, *GetBlogsOfUserRequest) (*GetBlogsOfUserResponse, error)
	mustEmbedUnimplementedBlogServiceServer()
}

// UnimplementedBlogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func (UnimplementedBlogServiceServer) CreatedBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatedBlog not implemented")
}
func (UnimplementedBlogServiceServer) MultiGetBlogs(context.Context, *MultiGetBlogsRequest) (*MultiGetBlogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiGetBlogs not implemented")
}
func (UnimplementedBlogServiceServer) GetBlogsOfUser(context.Context, *GetBlogsOfUserRequest) (*GetBlogsOfUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogsOfUser not implemented")
}
func (UnimplementedBlogServiceServer) mustEmbedUnimplementedBlogServiceServer() {}

// UnsafeBlogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServiceServer will
// result in compilation errors.
type UnsafeBlogServiceServer interface {
	mustEmbedUnimplementedBlogServiceServer()
}

func RegisterBlogServiceServer(s grpc.ServiceRegistrar, srv BlogServiceServer) {
	s.RegisterService(&BlogService_ServiceDesc, srv)
}

func _BlogService_CreatedBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreatedBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlogService/CreatedBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreatedBlog(ctx, req.(*CreateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_MultiGetBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiGetBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).MultiGetBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlogService/MultiGetBlogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).MultiGetBlogs(ctx, req.(*MultiGetBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_GetBlogsOfUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogsOfUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).GetBlogsOfUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlogService/GetBlogsOfUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).GetBlogsOfUser(ctx, req.(*GetBlogsOfUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogService_ServiceDesc is the grpc.ServiceDesc for BlogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatedBlog",
			Handler:    _BlogService_CreatedBlog_Handler,
		},
		{
			MethodName: "MultiGetBlogs",
			Handler:    _BlogService_MultiGetBlogs_Handler,
		},
		{
			MethodName: "GetBlogsOfUser",
			Handler:    _BlogService_GetBlogsOfUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BlogService.proto",
}
