// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package NewsFeedDB

import (
	"context"
	"database/sql"
)

const addNewsFeed = `-- name: AddNewsFeed :execresult
INSERT INTO NewsFeed (UserId, BlogId, Score)
VALUES
(?, ?, ?)
`

type AddNewsFeedParams struct {
	Userid int32
	Blogid int32
	Score  int32
}

func (q *Queries) AddNewsFeed(ctx context.Context, arg AddNewsFeedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewsFeed, arg.Userid, arg.Blogid, arg.Score)
}

const getNewsFeed = `-- name: GetNewsFeed :execresult
SELECT userid, blogid, score FROM NewsFeed
WHERE UserId=?
ORDER BY Score DESC
LIMIT ? OFFSET ?
`

type GetNewsFeedParams struct {
	Userid int32
	Limit  int32
	Offset int32
}

func (q *Queries) GetNewsFeed(ctx context.Context, arg GetNewsFeedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, getNewsFeed, arg.Userid, arg.Limit, arg.Offset)
}
