// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package UserDB

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (Username, Avatar, Password)
VALUES
(?, ?, ?)
`

type CreateUserParams struct {
	Username string
	Avatar   sql.NullString
	Password sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Username, arg.Avatar, arg.Password)
}

const getUserFromUserId = `-- name: GetUserFromUserId :one
SELECT id, username, avatar, password FROM users WHERE Id=?
`

func (q *Queries) GetUserFromUserId(ctx context.Context, id sql.NullInt32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromUserId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Avatar,
		&i.Password,
	)
	return i, err
}

const getUserFromUsername = `-- name: GetUserFromUsername :one
SELECT id, username, avatar, password FROM users WHERE Username=?
`

func (q *Queries) GetUserFromUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Avatar,
		&i.Password,
	)
	return i, err
}
