// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package BlogDB

import (
	"database/sql"
)

type Blog struct {
	ID          sql.NullInt32
	Title       string
	Privacy     int32
	Createdtime int64
	Updatedtime int64
	Author      int32
	Content     string
}
