# unit test read config
test:
  test: test
server:
  host: localhost:9001
  JWTPrivateKey: WaitingForYou
UserService:
  host: 0.0.0.0:9002
RelationshipService:
  host: 0.0.0.0:9003
BlogService:
  host: 0.0.0.0:9004
client:
  domain: http://localhost:3000
  domainCookie: 127.0.0.1:9001
projectName: WebServer
