// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: NewsFeedService.proto

package GrpcNewsFeedService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNewsFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit  int32 `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetNewsFeedRequest) Reset() {
	*x = GetNewsFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NewsFeedService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewsFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsFeedRequest) ProtoMessage() {}

func (x *GetNewsFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NewsFeedService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsFeedRequest.ProtoReflect.Descriptor instead.
func (*GetNewsFeedRequest) Descriptor() ([]byte, []int) {
	return file_NewsFeedService_proto_rawDescGZIP(), []int{0}
}

func (x *GetNewsFeedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNewsFeedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetNewsFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNewsFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId []int32 `protobuf:"varint,1,rep,packed,name=BlogId,proto3" json:"BlogId,omitempty"`
}

func (x *GetNewsFeedResponse) Reset() {
	*x = GetNewsFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NewsFeedService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewsFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsFeedResponse) ProtoMessage() {}

func (x *GetNewsFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_NewsFeedService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsFeedResponse.ProtoReflect.Descriptor instead.
func (*GetNewsFeedResponse) Descriptor() ([]byte, []int) {
	return file_NewsFeedService_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewsFeedResponse) GetBlogId() []int32 {
	if x != nil {
		return x.BlogId
	}
	return nil
}

var File_NewsFeedService_proto protoreflect.FileDescriptor

var file_NewsFeedService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x4e, 0x65, 0x77, 0x73, 0x46, 0x65, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x77, 0x73, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x67,
	0x49, 0x64, 0x32, 0x4b, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x73, 0x46, 0x65, 0x65, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73,
	0x46, 0x65, 0x65, 0x64, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x77, 0x73, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x47, 0x72, 0x70, 0x63, 0x4e, 0x65, 0x77, 0x73, 0x46, 0x65, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_NewsFeedService_proto_rawDescOnce sync.Once
	file_NewsFeedService_proto_rawDescData = file_NewsFeedService_proto_rawDesc
)

func file_NewsFeedService_proto_rawDescGZIP() []byte {
	file_NewsFeedService_proto_rawDescOnce.Do(func() {
		file_NewsFeedService_proto_rawDescData = protoimpl.X.CompressGZIP(file_NewsFeedService_proto_rawDescData)
	})
	return file_NewsFeedService_proto_rawDescData
}

var file_NewsFeedService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_NewsFeedService_proto_goTypes = []interface{}{
	(*GetNewsFeedRequest)(nil),  // 0: GetNewsFeedRequest
	(*GetNewsFeedResponse)(nil), // 1: GetNewsFeedResponse
}
var file_NewsFeedService_proto_depIdxs = []int32{
	0, // 0: NewsFeedService.GetNewsFeed:input_type -> GetNewsFeedRequest
	1, // 1: NewsFeedService.GetNewsFeed:output_type -> GetNewsFeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NewsFeedService_proto_init() }
func file_NewsFeedService_proto_init() {
	if File_NewsFeedService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_NewsFeedService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewsFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NewsFeedService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewsFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NewsFeedService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_NewsFeedService_proto_goTypes,
		DependencyIndexes: file_NewsFeedService_proto_depIdxs,
		MessageInfos:      file_NewsFeedService_proto_msgTypes,
	}.Build()
	File_NewsFeedService_proto = out.File
	file_NewsFeedService_proto_rawDesc = nil
	file_NewsFeedService_proto_goTypes = nil
	file_NewsFeedService_proto_depIdxs = nil
}
